service-providers:
- sp-url: http://localhost:9091/a
  sp-cert: ./samlsp.crt
  sp-key: ./samlsp.key
  idp-metadata: https://mocksaml.com/api/saml/metadata
- name: b
  sp-url: http://localhost:9091/b
  sp-cert: ./samlsp.crt
  sp-key: ./samlsp.key
  idp-metadata: https://mocksaml.com/api/saml/metadata
